### ISSUE TITLE
Customisable port

### ISSUE THREAD

**Issue by Fastidious** [nanoblog/nanoblog#1]
Add the ability to use a different port, so an existing web server can be used to proxy to it.

**Comment by nanoblog** [comment]
You should be able to use a different port by setting the `-http-addr` flag e.g. `nanoblog-linux-amd64 --http-addr=:9999 --letsencrypt=false --http-host localhost`

Also possible by setting ENV variables for the Docker image now. Maybe that was the issue you ran into?

Thanks again for all the feedback you've contributed.
